### ISSUE TITLE
Error installing pylint for python3.7 on cygwin

### ISSUE THREAD

**Issue by pjtallon** [python/typed_ast#105]
Hello,

I had an issue that looked almost the same as https://github.com/python/typed_ast/issues/63 when trying to install pylint for python3.7 on cygwin.

Here is the issue I originally opened to pylint : https://github.com/PyCQA/pylint/issues/2886

As additional information :
pjtallon@------- ~
$ which gcc
/usr/bin/gcc

pjtallon@------- ~
$ gcc --version
gcc (GCC) 7.4.0

Best,
Julien

**Comment by ethanhs** [comment]
Cygwin is not manylinux compatible (it uses newlib instead of glibc) so typed_ast needs to be built from source on that platform. For now you can install the "python-devel" package and it should install fine.

**Comment by ethanhs** [comment]
I tested this and wheels seem non-optimal since they have the cygwin version in their platform tag. @pjtallon (and if in future someone else comes upon this) if you want to install typed_ast on cygwin, you need the following packages:
 - `pythonXY` where `XY` is a version like `37`
 - `pythonXY-devel` for Python headers we need
 - `gcc-core` for the compiler

With these packages installed you shouldn't have issues installing pylint, mypy, or typed_ast directly.

I think this issue can be closed (I don't have the permissions to)

**Comment by pjtallon** [comment]
Hello,

Thanks a lot for your answer.

I just tried your workaround, and it worked perfectly.
The missing package on my side was pythonXY-devel. I already had gcc-core.

Closing the issue :)
