### ISSUE TITLE
Fix compatibility with Python 3.8+

### ISSUE THREAD

**Issue by webknjaz** [python/typed_ast#108]
Currently, sdist build fails: https://travis-ci.com/aio-libs/multidict/jobs/200520595#L341-L368

And it looks like it tries to build `_ast27` which (I assume) is related to Python 2.7. Why is it needed under Python 3?

**Comment by ethanhs** [comment]
@webknjaz mypy 0.650 (which it looks like you are building) does not support Python3.8. typed_ast was moved to the standard library in 3.8. In addition the C implementation of pgen was removed, so typed_ast won't run on 3.8. If you update to the latest version of mypy, everything should work correctly, as it will use the built-in ast module instead of typed_ast, if available.

The _ast27 module is to parse Python 2 code, which mypy (which only runs under Python 3) supports checking.

**Comment by webknjaz** [comment]
Oh, I see. Thanks for pointing that out!
