### ISSUE TITLE
Aarch64 wheels not available on pypi

### ISSUE THREAD

**Issue by tbbharaj** [python/typed_ast#180]
It looks like aarch64 wheels are no longer available 1.5.0 version onwards on [pypi.org](https://pypi.org/project/typed-ast/1.5.0/#files).
Is it possible to enable them back?
`pip install typed-ast` builds from source and fails due to dependencies issues.

Thank you!

**Comment by hauntsaninja** [comment]
We lost the ability to make aarch64 wheels when Travis stopped working for us. 

If you provide a PR that builds aarch64 wheels, I can upload them. The build options on GA are using qemu emulation or cross compilation. I'd prefer a solution that plays nicely with cibuildwheel, doesn't affect build of existing wheels (since those builds have been well tested), and doesn't pull in any GitHub Action dependency that isn't widely used. 

Short of that, feel free to pin to less than 1.5.0

**Comment by tbbharaj** [comment]
@hauntsaninja I have this pull request https://github.com/python/typed_ast/pull/182 for building aarch64 wheels, would love to get some feedbacks/reviews on it. Thanks!

**Comment by srittau** [comment]
aarch64 wheels are now built and are part of the latest release. Thanks, @tbbharaj and @hauntsaninja!
